---
- name: "install nfs server package"
  apt:
    name: "{{ item }}"
    state: latest
  with_items: 
    - nfs-kernel-server 
    - nfs-common

- name: "ensure nfs server is started"
  service:
    name: "nfs-kernel-server"
    state: "started"
    enabled: true

- name: "ensure shared directory exists"
  file:
    path: /share
    state: directory

- name: "add clients to exports file"
  template:
    src: ./exports.j2
    dest: /etc/exports
  notify: "restart nfs server"