# This playbook removes the references to the Enterprise Proxmox repository and replaces it with the No Subscription repository.

- hosts: all
  become: true
  remote_user: root
  tasks:
    - name: check if pve-enterprise.list exists
      stat: 
        path: /etc/apt/sources.list.d/pve-enterprise.list
      register: pve_enterprise_list

    - name: copy pve-enterpise.list (if exists)
      copy:
        remote_src: true
        src: /etc/apt/sources.list.d/pve-enterprise.list
        dest: /etc/apt/sources.list.d/pve-enterpise.list.bak
      when: pve_enterprise_list.stat.exists
    
    - name: check if ceph.list exists
      stat: 
        path: /etc/apt/sources.list.d/ceph.list
      register: ceph_list
    
    - name: copy ceph.list (if exists)
      copy: 
        remote_src: true 
        src: /etc/apt/sources.list.d/ceph.list
        dest: /etc/apt/sources.list.d/ceph.list.bak
      when: ceph_list.stat.exists
    
    - name: remove original pve-enterpise.list
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent
    
    - name: remove original ceph.list
      file:
        path: /etc/apt/sources.list.d/ceph.list
        state: absent

    - name: add NoSubscription repo list
      lineinfile:
        path: /etc/apt/sources.list.d/pve-no-sub-repo.list
        state: present
        create: true
        line: "deb [trusted=yes] http://download.proxmox.com/debian/pve bookworm pve-no-subscription"